### ISSUE TITLE
راه اندازی هوشمند

### ISSUE THREAD

**Issue by MrAli-71** [chabok-io/chabok-panel#4]
با سلام...در پنل مدیریت برای راه اندازی اولیه هنگام که از داخل دسترسی و توکن ها میخوام کتابخانه موبایل رو فعال کنم...در حالت راه اندازی هوشمند میزنم دانلود فایل برای اندروید غیر فعال هست..ممنون میشم بررسی کنید

**Comment by farbod-s** [comment]
<div dir="rtl">
سلام روز بخیر
نسخه ۳.۰.۰ کلاینت اندروید تازه منتشر شده و راه‌اندازی هوشمند پنل هم تا فردا شروع بکار میکنه.
<br>
لطفا ایمیل حساب کاربری و نوع حساب (سندباکس یا پروداکشن) رو بگید تا فایل رو براتون ایمیل کنم.
<br>
از مشکل بوجود اومده عذرخواهی می‌کنم.
</div>

**Comment by MrAli-71** [comment]
سندباکس

**Comment by MrAli-71** [comment]
ali.soley90@gmail.com

**Comment by farbod-s** [comment]
<div dir="rtl">
ارسال شد
<div>

**Comment by mjalijani** [comment]
سلام ، من از راه اندازی هوشمند استفاده کردم این خطا رو میگیرم 

  Process: com.yekaplus.yeka, PID: 25033
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/aidl/BaseStub;
        at com.android.installreferrer.api.InstallReferrerClientImpl.startConnection(InstallReferrerClientImpl.java:133)
        at com.adpdigital.push.WAW.startConnection(SourceFile:72)
        at com.adpdigital.push.TUY.run(SourceFile:38)
        at java.util.TimerThread.mainLoop(Timer.java:562)
        at java.util.TimerThread.run(Timer.java:512)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.aidl.BaseStub" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.yekaplus.yeka-5ks34J9i6305MpEb57ST2g==/base.apk"],nativeLibraryDirectories=[/data/app/com.yekaplus.yeka-5ks34J9i6305MpEb57ST2g==/lib/arm, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.android.installreferrer.api.InstallReferrerClientImpl.startConnection(InstallReferrerClientImpl.java:133) 
        at com.adpdigital.push.WAW.startConnection(SourceFile:72) 
        at com.adpdigital.push.TUY.run(SourceFile:38) 
        at java.util.TimerThread.mainLoop(Timer.java:562) 
        at java.util.TimerThread.run(Timer.java:512) 
علت این مشکل چیه ؟

**Comment by farbod-s** [comment]
<div dir="rtl">
سلام @mjalijani
<br>
در بخش dependencies در فایل build.gradle ماژول برنامه قطعه کد زیر را قرار بدید:
</div>

```
implementation 'com.android.installreferrer:installreferrer:1.0'
```
<div dir="rtl">
اگر این قطعه کد وجود دارد از یکسان بودن ورژن آن با کد بالا اطمینان پیدا کنید.
<br>
برای تست می‌تونید <a href="https://github.com/chabok-io/chabok-starter-android">پروژه نمونه</a> رو دریافت و اجرا کنید. در این پروژه راه‌اندازی اولیه و استفاده از قابلیت‌های چابک پیاده‌سازی شده.
<br>
<br>
سوالات مربوط به اندروید رو در بخش <a href="https://github.com/chabok-io/chabok-client-android/issues">مشکلات پروژه کلاینت اندروید چابک</a> بپرسید
<br>
ممنون
</div>
